
	CREATE DATABASE IF NOT EXISTS alcala;
    
    USE alcala;
    
    CREATE TABLE IF NOT EXISTS users(
		id INT NOT NULL AUTO_INCREMENT,
        name VARCHAR(50) NOT NULL,
        first_name VARCHAR(200) NOT NULL,
        clabe INT(4) NOT NULL UNIQUE,
        pin INT(4) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(id)
    );
    
    CREATE TABLE IF NOT EXISTS type_request(
		id INT NOT NULL AUTO_INCREMENT, 
        name VARCHAR(100) NOT NULL,
		created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(id)
    );
    
    CREATE TABLE IF NOT EXISTS balances(
		id INT NOT NULL AUTO_INCREMENT, 
        id_user INT NOT NULL,
        balance DECIMAL(15, 2) DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(id)
    );
    
    CREATE TABLE IF NOT EXISTS request(
		id INT NOT NULL AUTO_INCREMENT, 
        id_sender INT NOT NULL,
        id_receiver INT NOT NULL,
        id_type INT NOT NULL,
        amount DECIMAL(15, 2) DEFAULT 0,
        phone VARCHAR(12) NULL,
        latitude VARCHAR(20) NULL,
		longitude VARCHAR(20) NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(id)
    );
    
    
    ALTER TABLE balances ADD FOREIGN KEY (id_user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE NO ACTION;
    ALTER TABLE request ADD FOREIGN KEY (id_sender) REFERENCES balances(id) ON UPDATE CASCADE ON DELETE NO ACTION;
    ALTER TABLE request ADD FOREIGN KEY (id_receiver) REFERENCES balances(id) ON UPDATE CASCADE ON DELETE NO ACTION;
    ALTER TABLE request ADD FOREIGN KEY (id_type) REFERENCES type_request(id) ON UPDATE CASCADE ON DELETE NO ACTION;
    
    
    